import asyncio
import os
import structlog
from dotenv import load_dotenv
from anthropic import AsyncAnthropic

from src.services.mongodb_service import get_mongodb_service

# Configure structured logging
structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.processors.add_log_level,
        structlog.processors.StackInfoRenderer(),
        structlog.dev.set_exc_info,
        structlog.processors.TimeStamper(fmt="%H:%M:%S", utc=False),
        structlog.dev.ConsoleRenderer(colors=True),
    ],
    context_class=dict,
    logger_factory=structlog.PrintLoggerFactory(),
    cache_logger_on_first_use=True,
)
logger = structlog.get_logger()

# Load environment variables
load_dotenv()

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

# Use the most capable model available right now
EVALUATION_MODEL = "claude-opus-4-6"

async def fetch_qa_sample_with_chunks(db, model_name: str, sample_size: int = 5) -> list:
    """Fetch a random sample of QA pairs and their corresponding source chunks."""
    # 1. Fetch random QA pairs
    pipeline = [
        {"$match": {
            "metadata.generation_model": model_name
        }},
        {"$sample": {"size": sample_size}}
    ]
    
    cursor = db.wot_rag_qna.aggregate(pipeline)
    qa_docs = await cursor.to_list(length=sample_size)
    
    # 2. Fetch corresponding source chunks for each QA pair
    for doc in qa_docs:
        source_ids = doc.get("metadata", {}).get("source_chunk_ids", [])
        
        # Ensure source_ids is a list
        if isinstance(source_ids, str):
            source_ids = [source_ids]
            
        if source_ids:
            # Fetch chunks from rag_chunks collection
            chunks_cursor = db.rag_chunks.find({"chunk_id": {"$in": source_ids}})
            chunks = await chunks_cursor.to_list(length=None)
            
            chunk_texts = []
            for chunk in chunks:
                chunk_id = chunk.get("chunk_id", "Unknown ID")
                text_content = chunk.get("text_content", "")
                chunk_texts.append(f"[Chunk ID: {chunk_id}]\n{text_content}")
                
            if chunk_texts:
                doc["actual_source_text"] = "\n\n".join(chunk_texts)
            else:
                doc["actual_source_text"] = f"WARNING: Chunks with IDs {source_ids} not found in rag_chunks collection."
        else:
            doc["actual_source_text"] = "No source chunk IDs provided in metadata."
            
    return qa_docs

def format_qa_for_prompt(qa_docs: list) -> str:
    """Format QA documents and their source chunks into a readable string for the prompt."""
    formatted = []
    for i, doc in enumerate(qa_docs, 1):
        source_ids = doc.get("metadata", {}).get("source_chunk_ids", "N/A")
        formatted.append(f"--- Pair {i} ---")
        formatted.append(f"Reported Source Chunk IDs: {source_ids}")
        formatted.append(f"Actual Source Text from DB:\n{doc.get('actual_source_text', 'N/A')}")
        formatted.append(f"Question: {doc.get('question', 'N/A')}")
        formatted.append(f"Answer: {doc.get('answer', 'N/A')}")
        formatted.append("")
    return "\n".join(formatted)

async def main():
    if not ANTHROPIC_API_KEY:
        logger.error("ANTHROPIC_API_KEY not found in environment variables.")
        return

    # Initialize clients
    mongo_service = await get_mongodb_service()
    db = mongo_service.db
    anthropic_client = AsyncAnthropic(api_key=ANTHROPIC_API_KEY)

    logger.info("Starting QA quality evaluation script")
    logger.info("Using Anthropic model for evaluation", model=EVALUATION_MODEL)

    sample_size = 5

    # Fetch samples with actual chunk data
    logger.info("Fetching samples and source chunks from MongoDB...")
    pro_samples = await fetch_qa_sample_with_chunks(db, "models/gemini-3-pro-preview", sample_size)
    flash_samples = await fetch_qa_sample_with_chunks(db, "models/gemini-3-flash-preview", sample_size)

    if not pro_samples:
        logger.warning("No samples found for Gemini 3 Pro Preview.")
    if not flash_samples:
        logger.warning("No samples found for Gemini 3 Flash Preview.")

    if not pro_samples and not flash_samples:
        logger.error("No data to evaluate. Exiting.")
        return

    # Prepare the prompt
    prompt = f"""You are an expert evaluator of Question and Answer datasets for Retrieval-Augmented Generation (RAG) systems.
Your task is to compare the quality of QA pairs generated by two different AI models based on the same domain ("Wheel of Time" series).

Critically, you must evaluate whether the models correctly attributed the source chunks and whether the answers are fully grounded in the provided source text.

Here is a sample of {len(pro_samples)} QA pairs generated by Model A (Gemini 3 Pro):
{format_qa_for_prompt(pro_samples)}

Here is a sample of {len(flash_samples)} QA pairs generated by Model B (Gemini 3 Flash):
{format_qa_for_prompt(flash_samples)}

Please provide a detailed comparative analysis of the two models based on these samples. Focus on:
1. **Groundedness & Attribution (CRITICAL):** Can the correct answer to the question actually be derived entirely from the provided "Actual Source Text"? Did the model hallucinate information not present in the source chunks? Are the source chunk IDs accurately representing the information needed to answer the question?
2. **Question Complexity & Depth:** Are the questions trivial, or do they require deep understanding and synthesis of the source text?
3. **Answer Accuracy & Detail:** Are the answers comprehensive, accurate to the source text, and well-structured?
4. **Overall Suitability for RAG:** Which model produces better pairs for training/evaluating a RAG system, especially considering groundedness?

Conclude with a final verdict on whether the quality drop (if any) in Model B justifies the cost savings compared to Model A.
"""

    print("\n" + "="*80)
    print("EVALUATION PROMPT SENT TO ANTHROPIC")
    print("="*80)
    print(prompt)
    print("="*80 + "\n")

    logger.info("Sending evaluation prompt to Anthropic API...")
    
    try:
        response = await anthropic_client.messages.create(
            model=EVALUATION_MODEL,
            max_tokens=4000,
            temperature=0.2,
            system="You are an expert AI evaluator specializing in RAG datasets, focusing heavily on groundedness and hallucination detection.",
            messages=[
                {"role": "user", "content": prompt}
            ]
        )
        
        evaluation_result = response.content[0].text
        
        print("\n" + "="*80)
        print("ANTHROPIC EVALUATION REPORT")
        print("="*80)
        print(evaluation_result)
        print("="*80 + "\n")
        
        logger.info("Evaluation completed successfully.")
        
    except Exception as e:
        logger.error("Failed to generate evaluation", error=str(e))

if __name__ == "__main__":
    asyncio.run(main())
